/**
 * FACTS — generated by vet-site-generator. Do not hand-edit; regenerate
 * from the PracticeProfile instead. Types & helpers live in schema.ts.
 */

import type {
  Location,
  Clinic,
  Reviews,
  Accreditation,
  Service,
  Plan,
  PriceGroup,
  Post,
  NavItem,
} from "./schema";

export type { Location, Service, Plan } from "./schema";
export { fullAddress, mapEmbed, mapLink } from "./schema";

export const locations: Location[] = [
  {
    "name": "Rosevean Vets",
    "line1": "Coombe Rd",
    "area": "Penzance",
    "county": "Cornwall",
    "postcode": "TR18 3HU",
    "phone": "01736 362215",
    "phoneHref": "tel:+441736362215",
    "lat": 50.1204,
    "lng": -5.5342,
    "hours": [
      {
        "day": "Monday",
        "time": "8:00am – 6:30pm"
      },
      {
        "day": "Tuesday",
        "time": "8:00am – 6:30pm"
      },
      {
        "day": "Wednesday",
        "time": "8:00am – 6:30pm"
      },
      {
        "day": "Thursday",
        "time": "8:00am – 6:30pm"
      },
      {
        "day": "Friday",
        "time": "8:00am – 6:30pm"
      },
      {
        "day": "Saturday",
        "time": "9:00am – 1:00pm"
      },
      {
        "day": "Sunday",
        "time": "Closed"
      }
    ]
  }
];

export const clinic: Clinic = {
  "name": "Rosevean Vets",
  "shortName": "Rosevean",
  "logo": "/logo.avif",
  "heroImage": "",
  "tagline": "Your trusted 24-hour vets in Cornwall",
  "county": "Cornwall",
  "legalName": "Rosevean Veterinary Practice",
  "phone": {
    "main": "01736 362215",
    "mainHref": "tel:+441736362215"
  },
  "emergency": {
    "label": "24-hour emergency line",
    "phone": "01736 362215",
    "phoneHref": "tel:+441736362215"
  },
  "email": null,
  "facebook": null,
  "facebookStats": {
    "recommend": 0,
    "reviews": 0
  },
  "address": {
    "line1": "Coombe Rd",
    "town": "Penzance",
    "county": "Cornwall",
    "postcode": "TR18 3HU"
  },
  "hours": [
    {
      "day": "Monday",
      "time": "8:00am – 6:30pm"
    },
    {
      "day": "Tuesday",
      "time": "8:00am – 6:30pm"
    },
    {
      "day": "Wednesday",
      "time": "8:00am – 6:30pm"
    },
    {
      "day": "Thursday",
      "time": "8:00am – 6:30pm"
    },
    {
      "day": "Friday",
      "time": "8:00am – 6:30pm"
    },
    {
      "day": "Saturday",
      "time": "9:00am – 1:00pm"
    },
    {
      "day": "Sunday",
      "time": "Closed"
    }
  ]
};

export const reviews: Reviews = {
  "rating": 4.6,
  "count": 284,
  "source": "Google Reviews",
  "reviewedBy": "Google",
  "testimonials": [
    {
      "quote": "Friendly staff, clean premises, separation of dogs and cats, parking and I'm pleased with the individual care my cat received. There may be a wait, but you and your animal get the same care when it's their turn.",
      "author": "Karen Smith",
      "pet": "cat owner"
    },
    {
      "quote": "Care and understanding superb. They look after the owners as well as the pet. Customer care superb, always by all staff.",
      "author": "Elizabeth Holden",
      "pet": "dog owner"
    },
    {
      "quote": "Always been there when I needed them! Polite and helpful as always! Supportive when necessary on those sad occasions when a dog has come to the end of his or her life. Would recommend to anybody who needs veterinary help!",
      "author": "Jonathan Green",
      "pet": "dog owner"
    },
    {
      "quote": "Got an emergency appointment for my dog within two hours of calling. My dog had to stay for two nights and they took good care of him and called me regularly with updates. I felt he was in very good hands.",
      "author": "Amalie Gjelsvik",
      "pet": "dog owner"
    },
    {
      "quote": "Lovely to find such a nice vets. From the receptionists to the nurses and vets — everyone genuinely cares about the animals.",
      "author": "Diana Purchase",
      "pet": "cat owner"
    }
  ]
};

export const accreditations: Accreditation[] = [
  {
    "label": "RCVS Accredited Practice",
    "detail": "Royal College of Veterinary Surgeons"
  },
  {
    "label": "Cat Friendly Clinic Silver",
    "detail": "International Society of Feline Medicine"
  }
];

export const services: Service[] = [
  {
    "slug": "small-animal-consultations",
    "title": "Small Animal Consultations",
    "blurb": "Thorough consultations for dogs, cats, rabbits and small animals. Our experienced vets take the time to listen, examine and discuss your pet's health in full.",
    "icon": "stethoscope",
    "popular": true
  },
  {
    "slug": "diagnostics-imaging",
    "title": "Diagnostics & Imaging",
    "blurb": "In-house digital X-ray and ultrasound imaging for fast, clear answers. Our in-house laboratory analyses many tests within the practice, saving you and your pet valuable time.",
    "icon": "microscope",
    "popular": true
  },
  {
    "slug": "surgery",
    "title": "Surgery",
    "blurb": "Modern facilities and many years of experience performing soft tissue and orthopaedic surgeries on small animals, with full anaesthetic monitoring and skilled nursing care throughout.",
    "icon": "scalpel"
  },
  {
    "slug": "dental-care",
    "title": "Dental Care",
    "blurb": "Routine dental hygiene advice, professional scaling and polishing, and dental procedures as required. Good oral health is an essential part of your pet's overall wellbeing.",
    "icon": "stethoscope"
  },
  {
    "slug": "vaccinations-parasite-prevention",
    "title": "Vaccinations & Parasite Prevention",
    "blurb": "Routine vaccinations, boosters, microchipping, and tailored flea, tick and worm prevention to keep your pet protected through every stage of life.",
    "icon": "shield",
    "popular": true
  },
  {
    "slug": "nurse-clinics",
    "title": "Nurse Clinics",
    "blurb": "Our nursing team offers a range of dedicated clinics including weight management, senior cat checks, dental advice, and pre-hibernation checks for exotic pets.",
    "icon": "heart"
  },
  {
    "slug": "24-hour-emergency",
    "title": "24-Hour Emergency Care",
    "blurb": "We run our own round-the-clock emergency service for pets. Team members are onsite at all times, providing 24-hour care and monitoring for inpatients.",
    "icon": "heart",
    "popular": true
  },
  {
    "slug": "acupuncture",
    "title": "Acupuncture",
    "blurb": "Veterinary acupuncture involves placing fine needles into specific locations on the body to reduce pain, improve recovery rates and support long-term wellbeing.",
    "icon": "stethoscope"
  },
  {
    "slug": "pet-travel",
    "title": "Pet Travel",
    "blurb": "Travel advice, documentation and preparation to help you and your pet travel safely. We can provide Animal Health Certificates and health checks for international travel.",
    "icon": "shield"
  },
  {
    "slug": "referrals",
    "title": "Specialist Referrals",
    "blurb": "If we encounter a problem that requires specialist input, we have a wide network of referral centres and specialists to ensure your pet receives the expert care they need.",
    "icon": "stethoscope"
  },
  {
    "slug": "equine-services",
    "title": "Equine Services",
    "blurb": "A dedicated equine team providing 24-hour ambulatory vet services for horses, ponies and donkeys across Cornwall — from routine care to specialist procedures.",
    "icon": "paw",
    "popular": true,
    "sections": [
      {
        "heading": "Lameness & Pre-Purchase Examinations",
        "paragraphs": [
          "Our experienced equine vets can investigate and diagnose lameness issues and carry out pre-purchase examinations for horses intended for a full range of uses."
        ],
        "bullets": [
          "Lameness investigation and diagnosis",
          "Pre-purchase examinations (1-2 or 5-stage vettings)",
          "X-ray and ultrasound diagnostics"
        ]
      },
      {
        "heading": "Diagnostics & Laboratory",
        "paragraphs": [
          "We have mobile digital X-ray and ultrasound equipment, and offer a wide range of in-house clinical pathology services including haematology, worm egg counts, urinalysis and bacteriological culture."
        ],
        "bullets": [
          "Mobile digital X-ray and ultrasound",
          "Gastroscopy for stomach assessment and ulcer diagnosis",
          "Endoscopy of the upper respiratory tract",
          "In-house haematology and parasitology"
        ]
      },
      {
        "heading": "Surgical & Reproductive Services",
        "paragraphs": [
          "We offer castration services for horses, ponies and donkeys under standing sedation or general anaesthetic. Our equine stud medicine service is BEVA-approved for artificial insemination with fresh and chilled semen."
        ],
        "bullets": [
          "Castration under standing sedation or GA",
          "Reproductive and stud medicine services",
          "BEVA-approved AI with fresh and chilled semen"
        ]
      },
      {
        "heading": "Vaccinations & Dentistry",
        "paragraphs": [
          "We provide all vaccinations necessary to keep your horse safe and healthy, and offer routine dental care which is an essential part of every horse's primary care programme."
        ]
      },
      {
        "heading": "End of Life",
        "paragraphs": [
          "Saying goodbye is never easy. Our aim is to support you and provide a dignified, peaceful end for your horse when the time comes."
        ]
      }
    ]
  },
  {
    "slug": "farm-vet-services",
    "title": "Farm Vet Services",
    "blurb": "Our dedicated farm team provides advice and support across all areas of animal welfare and productivity — from dairy and beef cattle to sheep — including 24/7 emergency call-out.",
    "icon": "paw",
    "sections": [
      {
        "heading": "Dairy Services",
        "paragraphs": [
          "Comprehensive veterinary care for dairy herds to ensure optimal health and productivity, including mastitis management, fertility programmes, and routine herd health visits."
        ]
      },
      {
        "heading": "Beef Services",
        "paragraphs": [
          "Veterinary services tailored for beef cattle, covering health management, disease prevention, respiratory planning, and production efficiency support."
        ]
      },
      {
        "heading": "Sheep Services",
        "paragraphs": [
          "Support and advice for sheep farmers across West Cornwall, including lamb health, flock health planning, vaccinations and disease prevention."
        ]
      },
      {
        "heading": "TB Testing",
        "paragraphs": [
          "Our approved tuberculin testers (ATTs) carry out bovine TB testing across Cornwall. Contact us for TB test scheduling and herd movement paperwork."
        ]
      }
    ]
  }
];

export const planName: string | null = "Pet Health Plan";

export const carePlans: Plan[] = [
  {
    "name": "Dogs (small, up to 10kg)",
    "price": 21,
    "cadence": "per month",
    "summary": "Annual vaccinations, parasite prevention & one vet consultation",
    "features": [
      "Annual vaccinations",
      "Flea, tick & worm prevention",
      "One vet consultation",
      "Discount on neutering & dentals"
    ],
    "featured": true
  },
  {
    "name": "Dogs (medium, 10–25kg)",
    "price": 23,
    "cadence": "per month",
    "summary": "Annual vaccinations, parasite prevention & one vet consultation",
    "features": [
      "Annual vaccinations",
      "Flea, tick & worm prevention",
      "One vet consultation",
      "Discount on neutering & dentals"
    ]
  },
  {
    "name": "Dogs (large, 25–40kg)",
    "price": 25.75,
    "cadence": "per month",
    "summary": "Annual vaccinations, parasite prevention & one vet consultation",
    "features": [
      "Annual vaccinations",
      "Flea, tick & worm prevention",
      "One vet consultation",
      "Discount on neutering & dentals"
    ]
  },
  {
    "name": "Dogs (extra-large, 40kg+)",
    "price": 30.5,
    "cadence": "per month",
    "summary": "Annual vaccinations, parasite prevention & one vet consultation",
    "features": [
      "Annual vaccinations",
      "Flea, tick & worm prevention",
      "One vet consultation",
      "Discount on neutering & dentals"
    ]
  },
  {
    "name": "Cats",
    "price": 21,
    "cadence": "per month",
    "summary": "Annual vaccinations, parasite prevention & one vet consultation",
    "features": [
      "Annual vaccinations",
      "Flea, tick & worm prevention",
      "One vet consultation",
      "Discount on neutering & dentals"
    ]
  },
  {
    "name": "Rabbits",
    "price": 13,
    "cadence": "per month",
    "summary": "Annual vaccinations, parasite prevention & one vet consultation",
    "features": [
      "Annual vaccinations",
      "Parasite prevention",
      "One vet consultation"
    ]
  }
];

export const priceUpdated = "2026-06-30";

export const priceList: PriceGroup[] = [
  {
    "category": "Consultation & Preventative",
    "items": [
      { "service": "Consultation", "price": "£57" },
      { "service": "Dog booster vaccination", "price": "£65" },
      { "service": "Microchipping", "price": "£20" }
    ]
  }
];

export const posts: Post[] = [];

export const nav: NavItem[] = [
  {
    "label": "Home",
    "href": "/"
  },
  {
    "label": "About",
    "href": "/about"
  },
  {
    "label": "Services",
    "href": "/services"
  },
  {
    "label": "Contact",
    "href": "/contact"
  }
];
