/**
 * COPY — generated by vet-site-generator. Do not hand-edit; regenerate
 * from the PracticeProfile instead. Type lives in schema.ts.
 */

import type { SiteContent } from "./schema";

export const content: SiteContent = {
  "meta": {
    "baseUrl": "https://www.roseveanvets.co.uk",
    "defaultTitle": "Rosevean Vets | Trusted 24-Hour Vets in Penzance, Cornwall",
    "titleTemplate": "%s · Rosevean Vets",
    "description": "Rosevean Veterinary Practice in Penzance has been delivering quality veterinary care since 1837. Expert pet, equine and farm animal care, 24 hours a day across Cornwall.",
    "ogDescription": "Trusted vets in Penzance, Cornwall since 1837. Expert care for pets, horses and farm animals — 24 hours a day. Call 01736 362215.",
    "brandColor": "#b81c2e",
    "accentColor": "#0ea5e9"
  },
  "header": {
    "utilityNote": "Mon–Fri 8:00am–6:30pm · Sat 9:00am–1:00pm · 01736 362215"
  },
  "footer": {
    "blurb": "Rosevean Veterinary Practice has been providing compassionate veterinary care in Cornwall since 1837. Based in Penzance, our friendly team delivers the highest standards of care for pets, horses and farm animals — 24 hours a day.",
    "emergencyNote": "We run our own 24-hour emergency service. Call 01736 362215 at any time for urgent pet, equine or farm animal care.",
    "bottomTagline": "Trusted veterinary care in Cornwall since 1837",
    "finePrint": "© Rosevean Veterinary Practice · Coombe Rd, Penzance, Cornwall TR18 3HU"
  },
  "home": {
    "hero": {
      "badge": "Pets · Equine · Farm · Penzance, Cornwall",
      "headlineLines": [
        "Trusted Vets in Cornwall",
        "Since 1837"
      ],
      "body": "Based in Penzance, our friendly team of vets, nurses and support staff provide the highest standards of veterinary care for pets, horses and farm animals — 24 hours a day, every day."
    },
    "mission": {
      "eyebrow": "About Rosevean Vets",
      "heading": "Quality veterinary care for every animal, around the clock",
      "paragraphs": [
        "Rosevean Veterinary Practice has been at the heart of West Cornwall veterinary care since 1837. Our team of experienced vets, nurses and support staff are dedicated to delivering the highest standards of care for pets, horses and farm animals.",
        "We are proud of our RCVS-accredited status and our Cat Friendly Clinic Silver designation. With our own 24-hour emergency service, you can trust that expert help is always just a phone call away."
      ],
      "stats": [
        {
          "number": "Since 1837",
          "label": "Caring for Cornwall's animals"
        },
        {
          "number": "284+",
          "label": "Google reviews"
        },
        {
          "number": "24/7",
          "label": "Emergency service"
        },
        {
          "number": "3",
          "label": "Species specialisms"
        }
      ],
      "ctaLabel": "Meet our team"
    },
    "careClub": {
      "heading": "Always here when you need us",
      "body": "Unlike many practices, we run our own 24-hour emergency service. Our team is onsite at all times, providing round-the-clock care and monitoring for inpatients. Call 01736 362215 at any hour — day or night."
    },
    "location": {
      "eyebrow": "Find us",
      "heading": "Based in Penzance, Cornwall",
      "body": "Our practice is at Coombe Rd, Penzance TR18 3HU. We're open Monday to Friday 8:00am–6:30pm and Saturday 9:00am–1:00pm. Our equine and farm teams travel across West Cornwall. Emergency line always open: 01736 362215."
    },
    "advice": {
      "eyebrow": "Pet health advice",
      "heading": "Keeping your animals well"
    }
  },
  "reviews": {
    "eyebrow": "What our clients say"
  },
  "services": {
    "gridHeading": "Comprehensive care for pets, horses and farm animals",
    "gridBody": "From routine consultations and preventative care to specialist diagnostics, surgery, equine services and farm vet support — all backed by our own 24-hour emergency team in Penzance."
  },
  "finalCta": {
    "heading": "Ready to register with Rosevean Vets?",
    "body": "Whether you have a family pet, a horse or a livestock herd, we would be delighted to welcome you to our practice. New clients are always welcome — call us on 01736 362215 or drop in to Coombe Rd, Penzance."
  },
  "about": {
    "hero": {
      "eyebrow": "About us",
      "title": "Caring for Cornwall's animals since 1837",
      "intro": "Rosevean Veterinary Practice is one of Cornwall's oldest and most trusted vet practices. With deep roots in West Cornwall spanning nearly two centuries, our team of vets, nurses and support staff are proud to deliver the highest standards of care for pets, horses and farm animals — 24 hours a day."
    },
    "narrative": {
      "heading": "Our story",
      "paragraphs": [
        "Rosevean Veterinary Practice has been at the heart of West Cornwall for generations. Since our founding in the 1800s, we have grown from a small rural practice into a modern, full-service veterinary hospital — yet our values remain unchanged: compassionate, expert care for every animal we see.",
        "Today, our team of clinical directors, veterinary surgeons, nurses, technicians and support staff work together to provide comprehensive care for companion animals, horses and farm animals. We are RCVS Accredited and hold Cat Friendly Clinic Silver status — recognising our commitment to reducing stress for our feline patients.",
        "We are proud members of the VetPartners family, which allows us to invest in the very best equipment, training and facilities while maintaining the personal, friendly service our clients have come to expect."
      ]
    },
    "values": [
      {
        "title": "Caring since 1837",
        "text": "We have been a trusted part of the West Cornwall community for nearly two centuries. Our long history reflects a commitment to care that has endured through generations of local families and their animals."
      },
      {
        "title": "24-hour emergency care",
        "text": "Unlike many practices, we run our own 24-hour emergency service with team members onsite at all times. Whenever you need us — day or night — we are here."
      },
      {
        "title": "RCVS Accredited",
        "text": "Our RCVS-accredited status reflects the high standards we hold ourselves to in clinical governance, facilities, nursing care and client communication."
      },
      {
        "title": "Three-species expertise",
        "text": "Whether you have a companion animal, a horse, or a livestock herd, our specialist teams have the knowledge and experience to provide the right care — under one roof in Penzance."
      }
    ],
    "team": {
      "eyebrow": "Our people",
      "heading": "Meet our team",
      "members": [
        {
          "name": "Matthew Berriman",
          "photo": "/images/team/matthew-berriman.avif",
          "icon": "stethoscope",
          "role": "Senior Clinical Director & Vet Surgeon",
          "bio": "Matthew leads the clinical team at Rosevean, bringing extensive veterinary expertise and a deep commitment to the highest standards of care for all animals."
        },
        {
          "name": "Jenna Elliott",
          "photo": "/images/team/jenna-elliott.avif",
          "icon": "stethoscope",
          "role": "Clinical Director & Senior Vet Surgeon",
          "bio": "Jenna is a senior veterinary surgeon and Clinical Director with a wide range of expertise across small animal medicine and surgery."
        },
        {
          "name": "Fynn Stewart",
          "photo": "/images/team/fynn-stewart.avif",
          "icon": "stethoscope",
          "role": "Clinical Director & Vet Surgeon",
          "bio": "Fynn brings energy and expertise to the clinical team, working across all areas of small animal care as one of our three Clinical Directors."
        },
        {
          "name": "Anita Rennie",
          "photo": "/images/team/anita-rennie.avif",
          "icon": "stethoscope",
          "role": "Veterinary Surgeon",
          "bio": "Anita is a compassionate and experienced vet, dedicated to delivering excellent clinical care for pets and their families."
        },
        {
          "name": "Louise Moyle",
          "photo": "/images/team/louise-moyle.avif",
          "icon": "heart",
          "role": "Head Veterinary Nurse",
          "bio": "Louise leads our nursing team with dedication and skill, ensuring every patient receives exceptional care throughout their visit."
        },
        {
          "name": "Kensa Pepperell",
          "photo": "/images/team/kensa-pepperell.avif",
          "icon": "paw",
          "role": "Practice Manager",
          "bio": "Kensa keeps Rosevean running smoothly, ensuring every aspect of the practice runs to the high standards our clients expect."
        },
        {
          "name": "Charlotte Power-Kane",
          "photo": "/images/team/charlotte-power-kane.avif",
          "icon": "stethoscope",
          "role": "Veterinary Surgeon",
          "bio": "Charlotte is a skilled veterinary surgeon who brings warmth and clinical expertise to every patient she sees."
        },
        {
          "name": "Kieren Mitchell",
          "photo": "/images/team/kieren-mitchell.avif",
          "icon": "stethoscope",
          "role": "Veterinary Surgeon",
          "bio": "Kieren is an experienced vet with a commitment to delivering the highest quality care for companion animals across our caseload."
        }
      ],
      "note": "Rosevean Vets is home to a team of over 35 dedicated vets, nurses, technicians and support staff."
    }
  },
  "servicesPage": {
    "hero": {
      "eyebrow": "Our services",
      "title": "Expert care for pets, horses and farm animals",
      "intro": "From routine consultations and preventative health plans to specialist diagnostics, surgery, equine ambulatory care and farm vet support — Rosevean Vets provides comprehensive veterinary services for companion animals, horses and farm animals across Cornwall."
    },
    "processHeading": "What to expect when you visit",
    "journey": [
      {
        "step": "1",
        "title": "Get in touch",
        "text": "Call 01736 362215 to book an appointment. We're open Monday to Friday 8:00am–6:30pm and Saturday 9:00am–1:00pm. For equine or farm bookings, our dedicated teams can arrange visits at your yard or holding."
      },
      {
        "step": "2",
        "title": "Arrive at our practice",
        "text": "Find us at Coombe Rd, Penzance TR18 3HU. Our friendly reception team will welcome you and your animal, and ensure you are seen promptly by the right member of our team."
      },
      {
        "step": "3",
        "title": "See one of our vets",
        "text": "Our experienced vets will carry out a thorough examination. Where needed, we can run in-house diagnostics, imaging and laboratory tests on the same visit to get you answers quickly."
      },
      {
        "step": "4",
        "title": "Ongoing care",
        "text": "Our nursing team provides continuity of care and is always on hand to answer your questions. And if you ever need us out of hours, our own 24-hour emergency service means help is always available on 01736 362215."
      }
    ]
  },
  "careClub": {
    "hero": {
      "eyebrow": "Pet Health Plan",
      "title": "Year-round care with convenient monthly payments",
      "intro": "Our Pet Health Plan makes it easy to keep your pet healthy throughout the year. Spread the cost of essential preventative care across manageable monthly payments and enjoy savings on additional treatments."
    },
    "priceHeading": "Plan pricing",
    "priceNote": "Prices shown are per month. Plans cover annual vaccinations, tailored parasite prevention, one vet consultation per year, and discounts on neutering and dental procedures. Contact us on 01736 362215for details.",
    "planHeading": "What's included in the Pet Health Plan",
    "planBody": "Our Pet Health Plan covers the essential preventative care your pet needs throughout the year. Prices are fixed and paid monthly, making budgeting easier and keeping your pet protected.",
    "planNote": "Call 01736 362215 to set up a plan or ask at reception during your next visit.",
    "whyEyebrow": "Why preventative care matters",
    "whyHeading": "Prevention is better than cure",
    "benefits": [
      "Annual vaccinations protect against serious and life-threatening diseases",
      "Regular parasite prevention keeps your pet and home safe year-round",
      "Routine health checks allow early detection of conditions before they become serious",
      "Dental care prevents painful tooth and gum disease from developing",
      "Monthly payments make budgeting for your pet's health easier"
    ]
  },
  "contact": {
    "hero": {
      "eyebrow": "Get in touch",
      "title": "We're here for you and your animals",
      "intro": "Find us at Coombe Rd, Penzance. Call us on 01736 362215 to book an appointment, ask for advice, or in an emergency — we're here 24 hours a day."
    },
    "emergencyBody": "We run our own 24-hour emergency service. Call 01736 362215 at any time — our team is onsite and ready to help."
  },
  "register": {
    "eyebrow": "New clients",
    "title": "Register with Rosevean Vets",
    "body": "Whether you have a family pet, a horse or a farm, we'd be delighted to welcome you to Rosevean Vets. Call us on 01736 362215 or come and see us at Coombe Rd, Penzance.",
    "reassurance": [
      "RCVS Accredited Practice and Cat Friendly Clinic Silver",
      "Trusted veterinary care in Cornwall since 1837",
      "Pet, equine and farm vet services under one roof in Penzance",
      "Our own 24-hour emergency service — no referral needed"
    ],
    "successBody": "Thank you for registering with Rosevean Vets. We'll be in touch shortly and look forward to meeting you and your animals."
  },
  "book": {
    "eyebrow": "Book an appointment",
    "title": "See one of our vets",
    "body": "Call 01736 362215 to book an appointment. We're open Monday to Friday 8:00am–6:30pm and Saturday 9:00am–1:00pm. For equine visits, our ambulatory team comes to you.",
    "urgentNote": "For emergencies outside opening hours, call 01736 362215. We run our own 24-hour emergency service with team members onsite at all times."
  }
};
